apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-env-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: virtual-env-operator
  template:
    metadata:
      labels:
        name: virtual-env-operator
    spec:
      serviceAccountName: virtual-env-operator
      containers:
        - name: virtual-env-operator
          image: virtualenvironment/virtual-env-operator:v0.2.1
          command:
          - virtual-env-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "virtual-env-operator"
