apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-name-env-placeholder
  labels:
    app: service-name-placeholder
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-name-placeholder
  template:
    metadata:
      labels:
        app: service-name-placeholder
        virtualEnv: app-env-placeholder
    spec:
      containers:
        - name: service-name-placeholder
          image: docker.io/virtualenvironment/go-demo-debug:latest
          imagePullPolicy: IfNotPresent #Always
          env:
            - name: envMark
              value: app-env-placeholder
            - name: url
              value: http://app-java:8080/demo
          ports:
            - containerPort: 8080
